runtime: nodejs
env: flex
automatic_scaling:
  max_num_instances: 6
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.9
resources:
  cpu: 2
  memory_gb: 6
  disk_size_gb: 30
readiness_check:
  app_start_timeout_sec: 1800
